/-
Copyright (c) 2026 CompPoly Contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Valerii Huhnin
-/
module

public import CompPolyBench.Common
public import CompPoly.Multivariate.CMvPolynomial

/-!
# Multivariate Benchmarks
-/

public section

open CompPoly

namespace CompPolyBench

/-- Number of variables used by multivariate evaluation benchmarks. -/
private def multivariateVars : Nat := 5

/-- Exponents generated by multivariate benchmarks are reduced modulo this value. -/
private def multivariateExponentMod : Nat := 16

/-- Number of generated coefficient slots for multivariate evaluation benchmarks. -/
private def multivariateTermSlots : Nat := 512

/-- Number of evaluation points used by multivariate evaluation benchmarks. -/
private def multivariatePointCount : Nat := 32

/-- Input-shape label for dense multivariate benchmarks. -/
private def multivariateDenseShape : String :=
  s!"{multivariateVars} vars, {multivariateTermSlots} generated terms, exponent<" ++
    s!"{multivariateExponentMod}, dense coeffs, {multivariatePointCount} points"

/-- Input-shape label for sparse multivariate benchmarks. -/
private def multivariateSparseShape : String :=
  s!"{multivariateVars} vars, {multivariateTermSlots} generated terms, exponent<" ++
    s!"{multivariateExponentMod}, one nonzero per 16 coeffs, {multivariatePointCount} points"

/-- Build a computable multivariate polynomial from generated coefficients. -/
private def buildCMvPolynomial {R : Type*} [CommSemiring R] [BEq R] [LawfulBEq R]
    (terms : Array R) : CPoly.CMvPolynomial multivariateVars R :=
  Id.run do
    let mut p : CPoly.CMvPolynomial multivariateVars R := 0
    for i in [0:terms.size] do
      let monomial : CPoly.CMvMonomial multivariateVars := Vector.ofFn fun j ↦
        (i / (j.val + 1)) % multivariateExponentMod
      p := p + CPoly.CMvPolynomial.monomial monomial (terms.getD i 0)
    pure p

/-- Benchmark dense multivariate evaluation over a generic prime `ZMod` field. -/
private def runDenseMultivariateZMod (modulus : Nat) [Fact (Nat.Prime modulus)]
    (key nameSuffix fieldName fieldTitle : String)
    (preset : BenchPreset) (gen : StdGen) :
    IO (BenchGroup × StdGen) := do
  let (terms, gen) := (zmodArray modulus multivariateTermSlots false).run gen
  let (points, gen) := (zmodArray modulus (multivariateVars * multivariatePointCount) false).run gen
  let poly := buildCMvPolynomial terms
  let evalPoint (offset : Nat) : Fin multivariateVars → ZMod modulus :=
    fun j ↦ points.getD ((offset + j.val) % points.size) 0
  let checksumIterations := digestPeriod multivariatePointCount
  let denseEval ← runTimedSpec
    { name := ("multivariate-dense-eval-" ++ nameSuffix), representation := "CMvPolynomial",
      method := "eval", field := fieldName, inputShape := multivariateDenseShape,
      digestIterations := checksumIterations }
    preset
    (fun i ↦ CPoly.CMvPolynomial.eval (evalPoint (i % multivariatePointCount)) poly) checksumZMod
  let denseHorner ← runTimedSpec
    { name := ("multivariate-dense-horner-" ++ nameSuffix), representation := "CMvPolynomial",
      method := "evalHorner", field := fieldName, inputShape := multivariateDenseShape,
      digestIterations := checksumIterations }
    preset
    (fun i ↦ CPoly.CMvPolynomial.evalHorner (evalPoint (i % multivariatePointCount)) poly)
    checksumZMod
  pure ({
    groupKey := key,
    title := "Multivariate dense evaluation (" ++ fieldTitle ++ ")",
    records := #[denseEval, denseHorner]
  }, gen)

/-- Benchmark sparse multivariate evaluation over a generic prime `ZMod` field. -/
private def runSparseMultivariateZMod (modulus : Nat) [Fact (Nat.Prime modulus)]
    (key nameSuffix fieldName fieldTitle : String)
    (preset : BenchPreset) (gen : StdGen) :
    IO (BenchGroup × StdGen) := do
  let (terms, gen) := (zmodArrayWithStride modulus multivariateTermSlots 16).run gen
  let (points, gen) := (zmodArray modulus (multivariateVars * multivariatePointCount) false).run gen
  let poly := buildCMvPolynomial terms
  let evalPoint (offset : Nat) : Fin multivariateVars → ZMod modulus :=
    fun j ↦ points.getD ((offset + j.val) % points.size) 0
  let checksumIterations := digestPeriod multivariatePointCount
  let sparseEval ← runTimedSpec
    { name := ("multivariate-sparse-eval-" ++ nameSuffix), representation := "CMvPolynomial",
      method := "eval", field := fieldName, inputShape := multivariateSparseShape,
      digestIterations := checksumIterations }
    preset
    (fun i ↦ CPoly.CMvPolynomial.eval (evalPoint (i % multivariatePointCount)) poly) checksumZMod
  let sparseHorner ← runTimedSpec
    { name := ("multivariate-sparse-horner-" ++ nameSuffix), representation := "CMvPolynomial",
      method := "evalHorner", field := fieldName, inputShape := multivariateSparseShape,
      digestIterations := checksumIterations }
    preset
    (fun i ↦ CPoly.CMvPolynomial.evalHorner (evalPoint (i % multivariatePointCount)) poly)
    checksumZMod
  pure ({
    groupKey := key,
    title := "Multivariate sparse evaluation (" ++ fieldTitle ++ ")",
    records := #[sparseEval, sparseHorner]
  }, gen)

/-- Run KoalaBear dense multivariate evaluation benchmarks. -/
private def runKoalaBearMultivariateDense (preset : BenchPreset) (gen : StdGen) :
    IO (BenchGroup × StdGen) := do
  let (terms, gen) := (koalaBearArray multivariateTermSlots false).run gen
  let (points, gen) := (koalaBearPoints (multivariateVars * multivariatePointCount)).run gen
  let poly := buildCMvPolynomial terms
  let evalPoint (offset : Nat) : Fin multivariateVars → KoalaBear.Field :=
    fun j ↦ points.getD ((offset + j.val) % points.size) 0
  let fastTerms := koalaBearFastArray terms
  let fastPoints := koalaBearFastArray points
  let fastPoly := buildCMvPolynomial fastTerms
  let fastEvalPoint (offset : Nat) : Fin multivariateVars → KoalaBear.Fast.Field :=
    fun j ↦ fastPoints.getD ((offset + j.val) % fastPoints.size) 0
  let checksumIterations := digestPeriod multivariatePointCount
  let denseEval ← runTimedSpec
    { name := "multivariate-dense-eval", representation := "CMvPolynomial", method := "eval",
      field := "KoalaBear.Field", inputShape := multivariateDenseShape,
      digestIterations := checksumIterations }
    preset
    (fun i ↦ CPoly.CMvPolynomial.eval (evalPoint (i % multivariatePointCount)) poly)
    checksumKoalaBear
  let fastDenseEval ← runTimedSpec
    { name := "multivariate-dense-eval-fast", representation := "CMvPolynomial", method := "eval",
      field := "KoalaBear.Fast.Field", inputShape := multivariateDenseShape,
      digestIterations := checksumIterations }
    preset
    (fun i ↦ CPoly.CMvPolynomial.eval (fastEvalPoint (i % multivariatePointCount))
      fastPoly)
    checksumKoalaBearFast
  let denseHorner ← runTimedSpec
    { name := "multivariate-dense-horner", representation := "CMvPolynomial",
      method := "evalHorner", field := "KoalaBear.Field", inputShape := multivariateDenseShape,
      digestIterations := checksumIterations }
    preset
    (fun i ↦ CPoly.CMvPolynomial.evalHorner (evalPoint (i % multivariatePointCount)) poly)
    checksumKoalaBear
  let fastDenseHorner ← runTimedSpec
    { name := "multivariate-dense-horner-fast", representation := "CMvPolynomial",
      method := "evalHorner", field := "KoalaBear.Fast.Field",
      inputShape := multivariateDenseShape, digestIterations := checksumIterations }
    preset
    (fun i ↦ CPoly.CMvPolynomial.evalHorner (fastEvalPoint (i % multivariatePointCount))
      fastPoly)
    checksumKoalaBearFast
  pure ({
    groupKey := "multivariate-dense-koalabear",
    title := "Multivariate dense evaluation (KoalaBear)",
    records := #[denseEval, denseHorner, fastDenseEval, fastDenseHorner]
  }, gen)

/-- Run KoalaBear sparse multivariate evaluation benchmarks. -/
private def runKoalaBearMultivariateSparse (preset : BenchPreset) (gen : StdGen) :
    IO (BenchGroup × StdGen) := do
  let (terms, gen) := (koalaBearArrayWithStride multivariateTermSlots 16).run gen
  let (points, gen) := (koalaBearPoints (multivariateVars * multivariatePointCount)).run gen
  let poly := buildCMvPolynomial terms
  let evalPoint (offset : Nat) : Fin multivariateVars → KoalaBear.Field :=
    fun j ↦ points.getD ((offset + j.val) % points.size) 0
  let fastTerms := koalaBearFastArray terms
  let fastPoints := koalaBearFastArray points
  let fastPoly := buildCMvPolynomial fastTerms
  let fastEvalPoint (offset : Nat) : Fin multivariateVars → KoalaBear.Fast.Field :=
    fun j ↦ fastPoints.getD ((offset + j.val) % fastPoints.size) 0
  let checksumIterations := digestPeriod multivariatePointCount
  let sparseEval ← runTimedSpec
    { name := "multivariate-sparse-eval", representation := "CMvPolynomial", method := "eval",
      field := "KoalaBear.Field", inputShape := multivariateSparseShape,
      digestIterations := checksumIterations }
    preset
    (fun i ↦ CPoly.CMvPolynomial.eval (evalPoint (i % multivariatePointCount)) poly)
    checksumKoalaBear
  let fastSparseEval ← runTimedSpec
    { name := "multivariate-sparse-eval-fast", representation := "CMvPolynomial", method := "eval",
      field := "KoalaBear.Fast.Field", inputShape := multivariateSparseShape,
      digestIterations := checksumIterations }
    preset
    (fun i ↦ CPoly.CMvPolynomial.eval (fastEvalPoint (i % multivariatePointCount))
      fastPoly)
    checksumKoalaBearFast
  let sparseHorner ← runTimedSpec
    { name := "multivariate-sparse-horner", representation := "CMvPolynomial",
      method := "evalHorner", field := "KoalaBear.Field", inputShape := multivariateSparseShape,
      digestIterations := checksumIterations }
    preset
    (fun i ↦ CPoly.CMvPolynomial.evalHorner (evalPoint (i % multivariatePointCount)) poly)
    checksumKoalaBear
  let fastSparseHorner ← runTimedSpec
    { name := "multivariate-sparse-horner-fast", representation := "CMvPolynomial",
      method := "evalHorner", field := "KoalaBear.Fast.Field",
      inputShape := multivariateSparseShape, digestIterations := checksumIterations }
    preset
    (fun i ↦ CPoly.CMvPolynomial.evalHorner (fastEvalPoint (i % multivariatePointCount))
      fastPoly)
    checksumKoalaBearFast
  pure ({
    groupKey := "multivariate-sparse-koalabear",
    title := "Multivariate sparse evaluation (KoalaBear)",
    records := #[sparseEval, sparseHorner, fastSparseEval, fastSparseHorner]
  }, gen)

/-- Run Goldilocks dense multivariate evaluation benchmarks. -/
private def runGoldilocksMultivariateDense (preset : BenchPreset) (gen : StdGen) :
    IO (BenchGroup × StdGen) := do
  runDenseMultivariateZMod Goldilocks.fieldSize
    "multivariate-dense-goldilocks" "goldilocks" "Goldilocks.Field" "Goldilocks" preset gen

/-- Run Goldilocks sparse multivariate evaluation benchmarks. -/
private def runGoldilocksMultivariateSparse (preset : BenchPreset) (gen : StdGen) :
    IO (BenchGroup × StdGen) := do
  runSparseMultivariateZMod Goldilocks.fieldSize
    "multivariate-sparse-goldilocks" "goldilocks" "Goldilocks.Field" "Goldilocks" preset gen

/-- Runnable multivariate benchmark tasks. -/
def multivariateTasks : List BenchTask := [
  BenchTask.fromGroupRunner
    ⟨"multivariate-dense-koalabear", "Multivariate dense evaluation (KoalaBear)"⟩
    runKoalaBearMultivariateDense,
  BenchTask.fromGroupRunner
    ⟨"multivariate-sparse-koalabear", "Multivariate sparse evaluation (KoalaBear)"⟩
    runKoalaBearMultivariateSparse,
  BenchTask.fromGroupRunner
    ⟨"multivariate-dense-goldilocks", "Multivariate dense evaluation (Goldilocks)"⟩
    runGoldilocksMultivariateDense,
  BenchTask.fromGroupRunner
    ⟨"multivariate-sparse-goldilocks", "Multivariate sparse evaluation (Goldilocks)"⟩
    runGoldilocksMultivariateSparse
]

end CompPolyBench
